name: BuildPulse (Legacy Version)
description: |
  Deprecated: Use github.com/buildpulse/buildpulse-action instead
author: Jason Rudolph
branding:
  icon: "activity"
  color: "gray-dark"
inputs:
  account:
    description: |
      BuildPulse's unique numeric identifier for the account that owns the
      repository.
    required: true
  repository:
    description: |
      BuildPulse's unique numeric identifier for the repository.
    required: true
  path:
    description: |
      Path to the XML file(s) for the test results.

      The path can be a directory (e.g., "test/reports"), a single file (e.g.,
      "reports/junit.xml"), or a glob (e.g., "app/*/results/*.xml").
    required: true
  key:
    description: |
      BuildPulse access key ID for the account that owns the repository.

      In the GitHub settings for your repository, create an encrypted secret
      named BUILDPULSE_ACCESS_KEY_ID and set its value to the BuildPulse access
      key ID for your account. For help creating encrypted secrets, please see
      the GitHub docs at https://bit.ly/3Fjl4e7.

      Then, use the encrypted secret as the value for the 'key' input in your
      workflow. For help using a secret in a workflow, please see the GitHub
      docs at https://bit.ly/3LICKlE.
    required: true
  secret:
    description: |
      BuildPulse secret access key for the account that owns the repository.

      In the GitHub settings for your repository, create an encrypted secret
      named BUILDPULSE_SECRET_ACCESS_KEY and set its value to the BuildPulse
      secret access key for your account. For help creating encrypted secrets,
      please see the GitHub docs at https://bit.ly/3Fjl4e7.

      Then, use the encrypted secret as the value for the 'secret' input in your
      workflow. For help using a secret in a workflow, please see the GitHub
      docs at https://bit.ly/3LICKlE.
    required: true
  repository-path:
    description: |
      Path to the local git clone of the repository (default: ".").
    default: "."
    required: false
  commit:
    description: |
      Commit SHA for the commit that produced the test results.

      If your workflow checks out a *different* commit than the commit that
      triggered the workflow, then use this input to specify the commit SHA that
      your workflow checked out. For example, if your workflow is triggered by
      the `pull_request` event, but you customize the workflow to check out the
      pull request HEAD commit as described in https://bit.ly/37aEvcn, then
      you'll want to set this input to the pull request HEAD commit SHA.
    default: "${{ github.sha }}"
    required: false
runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/run.sh
      shell: bash
      continue-on-error: true
      env:
        INPUT_ACCOUNT: ${{ inputs.account }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_KEY: ${{ inputs.key }}
        INPUT_SECRET: ${{ inputs.secret }}
        INPUT_CLI_HOST: ${{ inputs.cli-host }} # Translate kebab-case input to snake_case env var
        INPUT_REPOSITORY_PATH: ${{ inputs.repository-path }} # Translate kebab-case input to snake_case env var
        INPUT_COMMIT: ${{ inputs.commit }}
