name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest

    steps:
      # https://github.com/actions/checkout/issues/335#issuecomment-827900176
      - name: Obtain latest Git ONLY within container for checkout
        run: |
          apt-get update
          apt-get install -y git

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm ci

      - run: npm test

      - name: Upload test results to BuildPulse for flaky test detection
        if: "!cancelled()" # Run this step even when the tests fail. Skip if the workflow is cancelled.
        uses: Workshop64/buildpulse-action@v0.7.0
        with:
          account: 46661156 # Replace this value with your BuildPulse account ID
          repository: 248253967 # Replace this value with your BuildPulse repository ID
          path: .
          key: ${{ secrets.BUILDPULSE_ACCESS_KEY_ID }}
          secret: ${{ secrets.BUILDPULSE_SECRET_ACCESS_KEY }}
