name: Publish Docker Image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: workshop64/buildpulse-github-action-runner
        add_git_labels: true
        tag_with_sha: true
        # When pushing to the master branch, tag the Docker image as 'latest'.
        # When pushing a new tag to the Git repo, apply the same tag to the
        # Docker image (e.g., 'v1.0.0').
        tag_with_ref: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
